### ISSUE TITLE
Data problems in tS sources (both desktop and Android)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/door43.org#499] opened 2017-03-21 19:31 UTC
As a translator I want to see all of the resources associated with the text of the English ULB so that I can make the best possible translation. (Currently there is a problem!)

I am posting this both here and in the tS repo to make sure that the right resources get applied to getting this fixed before we release 11.1 desktop and 11 Android.
Here is a list of misalignments between the ULB and its associated resources:
[OT_NT_validation_log.txt](https://github.com/unfoldingWord-dev/door43.org/files/859447/OT_NT_validation_log.txt)

**Comment by cckozie** [comment] 2017-03-22 20:06
Christine's analysis:
[missing chunks.xlsx](https://github.com/unfoldingWord-dev/door43.org/files/862718/missing.chunks.xlsx)

**Comment by phillip-hopper** [comment] 2017-03-28 19:30
@cckozie The problem is that tN is using a different chunking scheme than ULB. The correct solution is to make tN conform to the same scheme ULB is using.

**Comment by ChrisJarka** [comment] 2017-03-29 20:23
FYI - @phillip-hopper I don't believe that the tN is using a different chunking scheme because:
For the John 9:28 text:
**This is the ULB source - -**
\s5
\v 26 Then they said to him, "What did he do to you? How did he open your eyes?"
\v 27 He answered, "I have told you already, and you did not listen! Why do you want to hear it again? You do not want to become his disciples too, do you?

\s5
\v 28 They insulted him and said, "You are his disciple, but we are disciples of Moses.
\v 29 We know that God has spoken to Moses, but we do not know where this one is from."

\s5
\v 30 The man answered and said to them, "This is remarkable, that you do not know where he is from, and yet he opened my eyes.
\v 31 We know that God does not listen to sinners, but if someone is devout and does his will, he listens to him.

**This is the UDB source text - -** 
\s5
\v 26 So they said to him, "What did he do to you? How did he heal you so that you now see?"
\v 27 He answered them, "I have told you that already, but you did not believe me. Why do you want me to tell you again? Do you also really want to become his disciples?"

\s5
\v 28 Then they became angry and insulted him: "You are that man's disciple, but we are Moses' disciples!
\v 29 We know that God spoke to Moses; but about this man, we do not even know where he comes from."

\s5
\v 30 The man replied, "That is very amazing! You do not know where he comes from, but he is the one who opened my eyes so that I can see!
\v 31 We know that God does not listen to the prayers of sinners, those who ignore his law, but he listens to people who worship him and who do what he wants.

**This is the chunking scheme from the tN in door43.or/en/bible/notes/jhn**

John 09:24-25
John 09:26-27
John 09:28-29
John 09:30-31

**Comment by ChrisJarka** [comment] 2017-03-29 20:29
Here is the chunking scheme for John 14:30.

**From the ULB source text - -**

\s5
\p
\v 25 I have said these things to you, while I am staying with you.
\v 26 However, the Comforter—the Holy Spirit whom the Father will send in my name—he will teach you everything and he will remind you of everything that I said to you.
\v 27 I leave you peace; I give you my peace. I do not give it as the world gives. Do not let your heart be troubled, and do not be afraid.

\s5
\v 28 You heard that I said to you, 'I am going away, and I will come back to you.' If you loved me, you would be glad because I am going to the Father, for the Father is greater than I am.
\v 29 Now I have told you before it happens so that, when it happens, you will believe.

\s5
\v 30 I will no longer speak much with you, for the ruler of this world is coming. He has no power over me,
\v 31 but in order that the world will know that I love the Father, I do just as the Father commanded me. Let us get up and go from here."

**From the UDB source text ---**

\s5
\v 25 I have said these things to you while I am still with you.
\v 26 The Helper, the one who comes alongside to be with you—my Father will send him in my name. He will teach you everything that you need to know. He will also cause you to remember all the things that I have told you.
\v 27 As I leave you with peace, it is my peace that I am giving to you. I give you a kind of peace no one and nothing that belongs to this world can give you. So do not be upset or anxious; and do not be afraid.
\s5
\p
\v 28 You heard me say to you that I am going away and will later come back to you. If you loved me, you would be glad that I am going back to the Father because the Father is greater than I am.
\v 29 I have told you these things now before they happen so that, when they do happen, you will continue to trust me.
\s5
\v 30 I will not be able to talk with you much longer because the ruler of this world is coming. However, he has no power over me,
\v 31 and I will do what the Father has commanded me to do. This is so that the world will know forever that I love the Father. Come, let us go from here."

**This is the chunking scheme from the tN in door43.org/en/bible/notes/jhn/home**
John 14:25-27
John 14:28-29
John 14:30-31

**Comment by ChrisJarka** [comment] 2017-03-29 20:35
And lastly for the NT chunking errors - Here is for Luke 17:37. There is an error on the UDB for this text.

**The ULB source text has this chunking - -**

\s5
\v 32 Remember Lot's wife.
\v 33 Whoever seeks to gain his life will lose it, but whoever loses his life will save it.

\s5
\v 34 I tell you, in that night there will be two people in one bed. One will be taken, and the other will be left.
\v 35 There will be two women grinding together. One will be taken, and the other will be left."
\v 36 \f + \ft Luke 17:36 the best ancient copies omit, vs. 36 \fqa There will be two in the field; one will be taken and the other left. \f*
 
\s5
\v 37 They asked him, "Where, Lord?" and he said to them, "Where there is a body, there will the vultures also be gathered together."

**The UDB has this chunking - -**

\s5
\v 32 Remember what happened to Lot's wife!
\v 33 Anyone who continues in his own way of living will die. But anyone who leaves his way for my sake will live forever.

\s5
\v 34 I tell you this: On the night when I return, there will be two people sleeping in one bed. The one who believes in me will be taken and the other one will be left behind.
\v 35-36 Two women will be grinding grain together; one will be taken and the other left behind."
\v 37 His disciples said to him, "Lord, where will this happen?" He replied to them, "Wherever there is a dead body, the vultures will gather to eat it."

**The chunking at door43.org/en/bible/notes/luk/home is:**

Luke 17:32-33
Luke 17:34-36
Luke 17:37

**Comment by phillip-hopper** [comment] 2017-03-29 21:10
@ChrisJarka translationStudio does not use the chunking in ULB and UDB, that's the heart of the issue. The chunks used by tS can be found here: https://github.com/unfoldingWord-dev/uw-api/tree/develop/static/versification/ufw/chunks. In particular:

__Luke__: https://github.com/unfoldingWord-dev/uw-api/blob/develop/static/versification/ufw/chunks/luk.json

__John__: https://github.com/unfoldingWord-dev/uw-api/blob/develop/static/versification/ufw/chunks/jhn.json

**Comment by ChrisJarka** [comment] 2017-03-30 12:26
Sooo @phillip-hopper the tS versification file cannot be changed? 
This must have been for quite some time since Luk 17:37 has been in existence since 2016-03-18;  Jhn 14:30-31 since 2015-07-22; and Jhn 9:28-29 since 2015-04-09.

**Comment by lrsallee** [comment] 2017-03-30 14:09
We have had this debate multiple times over the past year. For some reason, tS keeps reverting to an outdated chunking scheme. The TN chunking has not changed for almost two years. This is a recurring tS problem that needs to be fixed.

**Comment by TomWarren** [comment] 2017-03-30 14:39
The ULB of LUK 17:36-17 has already been fixed in the ULB:

\v 36 \f + \ft Luke 17:36 the best ancient copies omit, vs. 36 \fqa There will be two in the field; one will be **taken and the other left. \f*
 
\s5
\v 37** They asked him, "Where, Lord?" and he said to them, "Where there is a body, there will the vultures also be gathered together."

The UDB of LUK 17:35-37 also has been fixed:

\s5
\v 34 I tell you this: On the night when I return, there will be two people sleeping in one bed. The one who believes in me will be taken and the other one will be left behind.
\v 35-36 Two women will be grinding grain together; one will be taken and the other left behind."

\s5
\v 37 His disciples said to him, "Lord, where will this happen?" He replied to them, "Wherever there is a dead body, the vultures will gather to eat it."

Thanks,

Tom

**Comment by lrsallee** [comment] 2017-03-30 14:42
Tom,

It is still incorrect in the USFM, so something did not update.

https://door43.org/en/udb/ep/43-luk.usfm

Larry

**Comment by TomWarren** [comment] 2017-03-30 15:23
The "n n" problem was fixed, Larry saw that it was in Chapt 18 at the first lines. The "n n" was removed and all is well.

Thanks Larry,

Tom

**Comment by phillip-hopper** [comment] 2017-03-30 15:45
@lrsallee translationStudio completely ignores the chunking in ULB and UDB. It has its own chunking system. You could remove all the chunk markers from the source USFM, and the results would be exactly the same. As a matter of fact, when we publish ULB and UDB, the first thing we do is remove all chunk markers.

**Comment by lrsallee** [comment] 2017-03-30 15:52
Phil,

The issue is not the markers. The issue is that tS is not following the chunk breaks we established three years ago. Someone way back used an incorrect list for tS and this is still haunting us.

Larry

**Closed** 2017-04-27 14:21 UTC
