### ISSUE TITLE
Web hook isn't activating to process updates

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/door43.org#819] opened 2018-03-23 15:24 UTC
As a reader and content technician, I want to be confident that changes to the repository are reflected on the live site. Currently, after some failures early in March, ULB and UDB failed to be updated unless the web hook was manually triggered.

**Comment by jag3773** [comment] 2018-03-23 17:02
This is by design and will be reactivated when we have the technical issues worked out.  I'm hoping that will be in April.

**Closed** 2018-10-31 15:40 UTC
