### ISSUE TITLE
Live Site: Right-to-Left languages not properly represented

### ISSUE THREAD

**Issue by eCyclops** [unfoldingWord-dev/door43.org#365] opened 2016-12-19 15:36 UTC
Door43 live site is displaying Right-to-Left scripts Left-to-Right

As a translator or Bible reader I want to be able to read Scripture in a language that reads right-to-left. Therefore, I need translation work that has been done in that language to display correctly in the live site. Currently, Right-to-Left languages display as Left-to-Right, which makes them very difficult to read. Example at https://live.door43.org/u/jdwood/glk_act_text_reg/0e7bea0316/

**Comment by jag3773** [comment] 2017-01-12 19:58
Duplicate of #324, which is being worked on in this sprint.

**Closed by jag3773** 2017-01-12 19:58 UTC
Labels: bug
